name: url-shortener
version: "3.8"

services:

  api:
    container_name: url-shortener-api
    restart: on-failure
    build:
      context: ./api/
      target: development
      dockerfile: ./Dockerfile
    image: url-shortener-api:1.0.0
    volumes:
      - ./api/app:/code/app
      - ./api/tests:/code/tests
      - ./api/run.py:/code/run.py
      - ./api/config.py:/code/config.py
      - ./api/.coverage:/code/.coverage
      - ./api/logs:/code/logs
      - ./db/migrations:/code/migrations
      - ./db/alembic:/code/alembic
      - ./db/alembic.ini:/code/alembic.ini
    env_file:
      - .env
    networks:
      - app-net
    ports:
      - 8000:80
    command: uvicorn app:app --reload --host 0.0.0.0 --port 80 && alembic init migrations

  db:
    container_name: url-shortener-db
    image: postgres:16
    env_file:
      - .env
    environment:
      - DB_HOST=localhost
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/sql/creates.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./db/sql/inserts.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      app-net:
        aliases:
          - db-host

  pgadmin:
    container_name: url-shortener-pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_USER}@${DB_NAME}.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
      - ./db/pgpass:/pgpass
    depends_on:
      - db
    networks:
      - app-net

networks:
    app-net:
